# Generated by Django 4.2.6 on 2023-11-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customer_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Address Line 2'),
        ),
    ]
