# Generated by Django 4.2.6 on 2023-11-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='created_by',
        ),
    ]
